server:
  port: 10002
myname: f
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qf4?serverTimezone=UTC
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 456123
