server:
  port:
    10002
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/qf4?serverTimezone=UTC
      username: root
      password: 456123
